### ISSUE TITLE
Export as PDF

### ISSUE THREAD

**Issue by guilhermeleobas** [dreampuf/GraphvizOnline#11]
Hi, is it possible to export the graph as a PDF rather than a png?

I can help implement this if you point me the direction.

**Comment by dreampuf** [comment]
Hi @guilhermeleobas 

I checked several solutions for PDF export in a pure Javascript way. They all implement in putting everything into an HTML element and convert it to SVG and then Canvas and serialize the canvas into an image. That image will be added to a PDF page as the final step. The resolution actually has been fixed in Canvas to the Image stage.

Does export as SVG is an option for you? I just add downloadable SVG support. 

- https://github.com/MrRio/jsPDF
- https://github.com/eKoopmans/html2pdf.js

**Comment by dreampuf** [comment]
I'd like to close this one as there is no more response.
