### ISSUE TITLE
Open in new tab on chrome

### ISSUE THREAD

**Issue by pizeyt** [dreampuf/GraphvizOnline#24]
Hi, 

I really appreciate this great utility, and use it in my work. 
Up until recently in Chrome I was able to right click on the SVG generated and 'Open in new tab'. 
That capability has gone, presumably a change in Chrome, it would be great if you were able to find a way of re-enabling it. 

best regards

**Comment by dreampuf** [comment]
Hi @pizeyt,

The change happens on #21. The wrapper of the A element has been removed due to its conflict with zoom and pan action. That's the reason you didn't see "open in new tab". Case there is no hyperlink on that HTML element. 

To complement the same goal, I added a "Download" button in the toolbar. You can right-click there to open the same result in the new tab.

Please let me know if that meets your need.

Best

**Comment by pizeyt** [comment]
You diamond!
Sorry not to realise that myself. 
This is perfect, I thought it was a change in Chrome, thank you for both the implementation and the explanation.
