### ISSUE TITLE
Share a graph

### ISSUE THREAD

**Issue by stepancheg** [dreampuf/GraphvizOnline#7]
Happy using your service, have a feature request: a button to share a link to the graph. The button may store a text in the get parameter optionally followed by some URL shortener.

**Comment by dreampuf** [comment]
After a little investigation, I found https://git.io would be a simple solution for URL shortener, specially for this GitHub project. Others like t.co, bitly.com or some random service yerl.org have more or fewer disadvantages. BTW, Google killed theirs (goo.gl) again. 
Thank you for raising it.

**Comment by dreampuf** [comment]
Due to git.io CORS policy, I can't get the shorter URL. But I do implement a URL generator. Please have a look.

https://dreampuf.github.io/GraphvizOnline/#digraph%20G%20%7B%0A%0A%20%20subgraph%20simple_solution%20%7B%0A%20%20%20%20style%3Dfilled%3B%0A%20%20%20%20color%3Dlightgrey%3B%0A%20%20%20%20node%20%5Bstyle%3Dfilled%2Ccolor%3Dwhite%5D%3B%0A%20%20%20%20a0%20-%3E%20a1%20-%3E%20a2%20-%3E%20a3%3B%0A%20%20%20%20label%20%3D%20%22process%20%231%22%3B%0A%20%20%7D%0A%7D

**Comment by stepancheg** [comment]
Thank you! Sharing works perfectly. Although the link is displayed outside of the windows in my browser.

<img width="637" alt="2018-11-20_0246" src="https://user-images.githubusercontent.com/28969/48748380-a4308100-ec6e-11e8-978e-6932d8672d18.png">

Maybe instead of text field it could simply update an href of the current browser page, text field won't be needed.

(I'm fine without shortener, pasting a link into tinyurl.com is not that hard).

**Comment by dreampuf** [comment]
Here some updates:
- add `history.pushState` for successful render
- support `history.back` event
- bit.ly shortener (hopefully, it's safe to use my personal token)
